### ISSUE TITLE
IgCookieNotFoundError: Cookie "sessionid" not found

### ISSUE THREAD

**Issue by eslam2511** [Nerixyz/instagram_mqtt#121] opened 2024-08-27 11:49 UTC
I get this error when I try to connect 

```
IgCookieNotFoundError: Cookie "sessionid" not found
    at State.extractCookieValue (/home/runner/ReelDownloaderBot/node_modules/instagram-private-api/dist/core/state.js:153:19)
    at RealtimeClient.constructConnection (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:45:89)
    at MQTToTClient.payloadProvider [as connectPayloadProvider] (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:95:22)
    at MQTToTClient.connect (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/mqttot/mqttot.client.js:54:42)
    at /home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:140:23
    at new Promise (<anonymous>)
    at RealtimeClient.connect (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:127:16)
    at RealtimeClient.wrapper (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/mixins/mixin.js:24:35)
    at RealtimeClient.wrapper (/home/runner/ReelDownloaderBot/node_modules/instagram_mqtt/dist/realtime/mixins/mixin.js:24:35)
    at postToInsta (file:///home/runner/ReelDownloaderBot/index.js:16:23)
```

and here is my code 

```
import { IgApiClient } from "instagram-private-api";
import mqtt from "instagram_mqtt";
const { IgApiClientRealtime, withRealtime } = mqtt;
const postToInsta = async () => {
  try {
    //Contect Instagram API Client
    const ig = withRealtime(new IgApiClient());
    ig.state.generateDevice(procces.env.USERNAME);
    await ig.account.login(procces.env.USERNAME, proccess.env.PASSWORD);
    //listen for messages
    ig.realtime.on('message', (m) => console.log(m.message))
    ig.realtime.on('error', console.error)
    ig.realtime.on('close', () => console.error("RealtimeClient closed"))
    await ig.realtime.connect();
    setInterval(async () => {
      

      
      console.log("listening..");
    }, 10000);

  } catch (err) {
    return err;
  }
};

function logEvent(name) {
  return (data) => console.log(name, data);
}

postToInsta();

**Comment by Nerixyz** [comment] 2024-08-27 12:48
Duplicate of #120.

**Closed as not planned by Nerixyz** 2024-08-27 12:48 UTC

**Comment by eslam2511** [comment] 2024-08-27 13:06
> Duplicate of #120.

ya but it did not get fixed

**Comment by Nerixyz** [comment] 2024-08-27 13:16
> ya but it did not get fixed

The referenced issue is still open. Until it's closed, there's no need to open another one.
